/* USER */
export const CONNECT_USER = "CONNECT_USER";
export const DISCONNECT_USER = "DISCONNECT_USER";
export const FETCH_USERS_BEGIN = "FETCH_USERS_BEGIN";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

/* PROPOSITION */
export const SELECT_PROPOSITION = "SELECT_PROPOSITION"
export const FETCH_PROPOSITIONS_BEGIN = "FETCH_PROPOSITIONS_BEGIN";
export const FETCH_PROPOSITIONS_SUCCESS = "FETCH_PROPOSITIONS_SUCCESS";
export const FETCH_PROPOSITIONS_FAILURE = "FETCH_PROPOSITIONS_FAILURE";
export const UPDATE_PROPOSITIONS_BEGIN = "FETCH_PROPOSITIONS_BEGIN";
export const UPDATE_PROPOSITIONS_SUCCESS = "FETCH_PROPOSITIONS_SUCCESS";
export const UPDATE_PROPOSITIONS_FAILURE = "FETCH_PROPOSITIONS_FAILURE";
export const POST_PROPOSITIONS_BEGIN = "POST_PROPOSITIONS_BEGIN";
export const POST_PROPOSITIONS_SUCCESS = "POST_PROPOSITIONS_SUCCESS";
export const POST_PROPOSITIONS_FAILURE = "POST_PROPOSITIONS_FAILURE";
export const INVALIDATE_PROPOSITIONS = "INVALIDATE_PROPOSITIONS";

/* ANSWERS */
export const ADD_ANSWER = "ADD_ANSWER";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const FETCH_ANSWERS_BEGIN = "FETCH_ANSWERS_BEGIN";
export const FETCH_ANSWERS_SUCCESS = "FETCH_ANSWERS_SUCCESS";
export const FETCH_ANSWERS_FAILURE = "FETCH_ANSWERS_FAILURE";

/* TAGS */
export const FETCH_TAGS_BEGIN = "FETCH_TAGS_BEGIN";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_FAILURE = "FETCH_TAGS_FAILURE";

/* SLICE */
export const FETCH_SLICE_BEGIN = "FETCH_SLICE_BEGIN";
export const FETCH_SLICE_SUCCESS = "FETCH_SLICE_SUCCESS";
export const FETCH_SLICE_FAILURE = "FETCH_SLICE_FAILURE";
export const POST_SLICE_BEGIN = "POST_SLICE_BEGIN";
export const POST_SLICE_SUCCESS = "POST_SLICE_SUCCESS";
export const POST_SLICE_FAILURE = "POST_SLICE_FAILURE";
export const ADD_SLICE = "ADD_SLICE"