export const ADD_ANSWER = "ADD_ANSWER";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const CONNECT_USER = "CONNECT_USER";
export const DISCONNECT_USER = "DISCONNECT_USER";
export const REQUEST_PROPOSITIONS = "REQUEST_PROPOSITIONS";
export const INVALIDATE_PROPOSITIONS = "INVALIDATE_PROPOSITIONS";
export const RECEIVE_PROPOSITIONS = "RECEIVE_PROPOSITIONS";